//
// Created by 胡凌瑞 on 2021/1/16.
//

#ifndef REGULAR_EXPRESSION_ENGINE_GLOBALHEADER_H
#define REGULAR_EXPRESSION_ENGINE_GLOBALHEADER_H

const char DOLLAR = 3; //End of Text($)
const char EPSILON = 0; //NULL
const char BACKSPLASH = '\\';

#endif //REGULAR_EXPRESSION_ENGINE_GLOBALHEADER_H
